[package]
name = "example-tensorflow-rust"
version = "0.1.0"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
